#!/usr/bin/env sh

# Bind Docker ports to host ports so IPFS can reach the
# outside world. Also, run the machine as a daemon.
docker run -d -p 4001:4001 -p 5001:5001 -p 8080:8080 -p 21:21 -p 22:22 -p 30000-30009:30000-30009 $@
